apiVersion: v1
kind: Service
metadata:
  name: telegram-api
  labels:
    app: telegram-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8001
    targetPort: http
    protocol: TCP
  selector:
    app: telegram-api
---
apiVersion: v1
kind: Service
metadata:
  name: telegram-api-external
  labels:
    app: telegram-api
spec:
  type: LoadBalancer  # Или NodePort для k3s
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: telegram-api
