apiVersion: v1
kind: Service
metadata:
  name: telegram-bots
  labels:
    app: telegram-bots
spec:
  type: ClusterIP
  ports:
  - name: health
    port: 8002
    targetPort: health
    protocol: TCP
  selector:
    app: telegram-bots
